config/routes.rb
Rainforest::Application.routes.draw do
  get "reviews/show"
  get "reviews/new"
  get "reviews/edit"
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  get "users/new"
  get "users/create"
  resources :products do
    resources :reviews, :except => [:index]
  end

  scope "(:locale)", :locale => /en|jp/ do
    root :to => 'products#index'
    get "products/index"
  end
  

  resources :users, :only => [:new, :create]

  resources :sessions, :only => [:new, :create, :destroy]

  

end

app/models/product.rb
class Product < ActiveRecord::Base
 
	has_many :reviews
	has_many :users, :through => :reviews

	validates :description, :name, :presence => true
	validates :price_in_cents, :numericality => {:only_integer => true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product
	validates :comment, :presence => true
	validates_uniqueness_of :user_id, :scope => [:product_id]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates_presence_of :password, :on => :create
	validates :password, :length => 6..20
	validates :email, :uniqueness => true

	has_many :reviews
	has_many :products, :through => :reviews

	validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :set_locale

private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
    Rails.application.routes.default_url_options[:locale]= I18n.locale
  end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

  helper_method :current_user


  	def ensure_logged_in
  		unless current_user
  			flash[:alert] = "Please log in"
  			redirect_to new_session_path
  		end
  	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :ensure_logged_in, :only => [:show, :new]

  def index
    @search = Product.search(params[:q])
  	@products = @search.result.order('name').paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def show
  	@product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end

    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end

  def new
  	@product = Product.new

    respond_to do |format|
      format.html
      format.json { render json: @products }
    end
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new product_parameters
    respond_to do |format|
    	if @product.save
    		format.html { redirect_to @product, notice: I18n.t('views.product.flash_messages.product_was_successfully_created') }
        format.json { render json: @product, status: :created, location: @product }
    	else
    		format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
    	end
    end
  end

  def update
  	@product = Product.find(params[:id])

    respond_to do |format|
    	if @product.update_attributes product_parameters
    		format.html { redirect_to @product, notice: I18n.t('views.product.flash_messages.product_was_successfully_updated')}
        format.json { head :no_content }
    	else
    		format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
    	end
    end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
    
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
  def product_parameters
    params.require(:product).permit(:name, :description, :price_in_cents, :url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :ensure_logged_in, :only => [:edit, :create, :show, :update, :destroy]
	before_filter :load_product

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build params.require(:review).permit(:comment, :product_id, :user_id)
    @review.user_id = current_user.id

    respond_to do |format|
    	if @review.save
    		format.html {redirect_to product_path(@product),
          notice: 'Review created successfully!'}
        format.js {}
    	else
    		format.html {redirect_to product_path(@product),
           notice: 'You\'ve already reviewed this!'}
        format.js {}   
    	end
    end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private

  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end
 
  def create
  	@user = User.new user_parameters
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to products_url, :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  private
  def user_parameters
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> 
<head>
  <link href='http://fonts.googleapis.com/css?family=Raleway:300,700' rel='stylesheet' type='text/css'>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>


  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <%= yield %>
  
  <div class="lang_toggle">
    <%= link_to_unless I18n.locale == :en, "English", locale: :en %>
    |
    <%= link_to_unless I18n.locale == :jp, "日本語", locale: :jp %>
  </div>
    
  </body>
</html>

app/views/products/_form.html.erb
<div id="form"><%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
	  <div id="error_explanation">
	  	<h2><%= t 'activerecord.errors.template.header', :model => Product.model_name.human, :count => @product.errors.count %> </h2>

	  	<ul>
	  		<% @product.errors.full_messages.each do |msg| %>
	  		<li> <%= msg %></li>
	  		<% end %>
	  	</ul>
	  </div>
	<% end %>
	
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :description %></br>
		<%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :price_in_cents %></br>
		<%= f.number_field :price_in_cents %>
	</div>
	<div class="field">
		<%= f.label :url %></br>
		<%= f.text_field :url %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>
</div>

app/views/products/_reviews.html.erb
<% @product.reviews.each do |review| %>
	<p>
	  	<%= review.comment %>
	<br>
	  	<% if review.user != nil %>
	  	  <em> by <strong><%= review.user.name %></strong></em>
	  	  Added on: <%= review.created_at %>
	  	<% end %>
	</p>
<% end %>

app/views/products/edit.html.erb
<div class="top"><h1><%= t 'views.product.edit.title' %></h1><div>
<div> 

<p>
	<%= link_to I18n.t('views.back'), @product %>
</p>

<%= form_for @product do |f| %>
	<p>
		<%= f.label "name" %><br>
		<%= f.text_field "name" %>
	</p>
	<p>
		<%= f.label "description" %><br>
		<%= f.text_field "description" %>
	</p>
	<p>
		<%= f.label "price_in_cents" %><br>
		<%= f.text_field "price_in_cents" %>
	<p>
		<%= f.submit  %>
	</p>
<% end %>

app/views/products/index.html.erb
<div class="top"><h1><%= t '.title' %></h1>
<!-- 
<div class="language">
	<b>I18n.locale:</b>
	<%= I18n.locale %>
</div> -->

<div class="sign_in">
      <% if current_user %>
        <%= t '.status' %><%= current_user.name %>. 
        <%= link_to (t'.log_out'), session_path("current"), :method => :delete %>
      <% else %>
          <%= link_to (t '.log_in'), new_session_path %><br/>
        <%= link_to (t '.sign_up'), new_user_path %>
      <% end %></div>

    <p id="product_count"><%= t '.current_num' %>
      <strong><%= @products.length %></strong>
      <%= t '.products_available' %>
      <%= link_to (t '.new_product'), new_product_path %>
    </p>
</div>

<div class="info_box">
  <div class="pagination">
    <div class="search">
      <%= search_form_for @search do |f| %>
      <div class="field">
        <%= f.label :name_cont, (t '.search') %>
        <%= f.text_field :name_cont %>
      </div>
      <% end %>
    </div>
    <%= will_paginate @products %>
  </div>
  <% @products.each do |product| %>
	<div class="index_box">
    <div class="name_price"><%= link_to product.name,product %><br>
      <div class="index_pic"><%= link_to image_tag(product.url) %>
      </div>
		  <p class="price"><%= number_to_currency(product.formatted_price) %>
      </p>
  </div>
</div>
<% end %> 

app/views/products/index_.jp.html.erb
<div class="top"><h1>レインフォレストへようこそ！</h1>

<!-- <div class="language">
	<b>I18n.locale:</b>
	<%= I18n.locale %>
</div> -->

<div class="sign_in">
      <% if current_user %>
        アカウント名：<%= current_user.name %>. 
        <%= link_to "ロッグアウト", session_path("current"), :method => :delete %>
      <% else %>
          登録してあれば、<%= link_to "ロッグイン", new_session_path %>、<br/>それか、
        初めてなら<%= link_to "登録する", new_user_path %>
      <% end %></div>

<p id="product_count">現在<%= @products.length %>コの商品が保存してある.　<%= link_to "新しい商品", "/products/new" %>
</p></div>作りますか？

<div class="info_box"><% @products.each do |product| %>
	<div class="index_box"><div class="name_price"><%= link_to product.name, product %><br><div class="index_pic"><%= link_to image_tag(product.url) %></div>
		 <p class="price"><%= product.price_in_cents %>円</p></div></div>
<% end %> 

app/views/products/new.html.erb
<div class="top"><h1><%= t 'views.product.new.title' %></h1></div>

<%= render 'form' %>

<div id="back"><%= link_to I18n.t('views.back'), products_path %></div>

app/views/products/show.html.erb
<div class="top">
  <h1><%= t 'views.product.show.title' %><%= @product[:name] %> 
  </h1>

  <div>
    <p><%= link_to I18n.t('views.back'), products_url %> | <%= link_to I18n.t('views.edit'), edit_product_path(@product) %> | <%= link_to I18n.t('views.destroy'), @product, :confirm => "Are you sure you want to delete this product?", :method => :delete %></p>
  </div>
</div>
  <br>
    <div class="info_box">
      <div id="name_box"><%= Product.human_attribute_name(:name) %><br><%= @product.name %>
      </div> 
        <br>
    <div id="description_box"><%= Product.human_attribute_name(:description) %><br><%= @product.description %>
    </div>
        <br>
    <div id="price_box"><%= t 'views.product.show.price' %>$<%= @product.formatted_price %>
    </div>
        <br>
    <div id="picture"><%= link_to image_tag(@product.url) %>
    </div>
</div>

<% if current_user %>
	<div class="reviews"><h3>Reviews</h3>

	<p> Reviews for <%= @product.name %></p>
<div id="review-list">
	<%= render :partial => "products/reviews" %>
</div>
<% end %>

<% if current_user %>

<h4>New Review</h4>

  <%= form_for [@product, @review], :remote => true do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
        <div class="error_alert">
          <li><%= msg %></li>
        </div>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %></div>

app/views/reviews/create.js.erb
$("#review-list").html("<%= escape_javascript(render(:partial => '/products/reviews')) %>");

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="sign_up"><h1>Sign Up</h1>
 

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
    	<h2>Form is invalid</h2>
    	<ul>
    		<% for message in @user.errors.full_messages %>
    		  <li><%= message %></li>
    		<% end %>
    	</ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :email %><br/>
  	<%= f.text_field :email %>
  </div>
  <div class="field">
  	<%= f.label :password %><br/>
  	<%= f.password_field :password %>
  </div>
  <div class="field">
  	<%= f.label :password_confirmation %><br/>
  	<%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
</div>